# Generated by Django 5.1.7 on 2025-05-17 16:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_at', models.DateTimeField(auto_now_add=True)),
                ('accepter', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(blank=True, max_length=1000)),
                ('file', models.FileField(blank=True, null=True, upload_to='image/chat_image')),
                ('time_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lue', models.BooleanField(default=False)),
            ],
        ),
    ]
