# Generated by Django 5.1.7 on 2025-05-17 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Amis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='amis',
            name='demandeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandeur_invitation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='amis',
            name='recepteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepteur_invitation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='user_recive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_recive', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='user_send',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_send', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='amis',
            unique_together={('demandeur', 'recepteur')},
        ),
    ]
